version: 3

tasks:
  build-bin-linux:
    internal: true
    desc: "reusable build task"
    env:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    cmd: go build -v -tags with_reality_server -o ./bin/$GOOS-$GOARCH/{{ .APP }} ./cmd/{{ .APP }}/

  build-unchained-linux:
    desc: "build `unchained` app for linux"
    cmds:
      - task: build-bin-linux
        vars:
          APP: unchained

  build-worker-linux:
    desc: "build `unchained-worker` app for linux"
    cmds:
      - task: build-bin-linux
        vars:
          APP: unchained-worker

  build-linux:
    desc: "build all apps for linux"
    cmds:
      - task: build-unchained-linux
      - task: build-worker-linux
